### ISSUE TITLE
Two calendar components gets created when changing months from default path

### ISSUE THREAD

**Issue by skindstrom** [SimonKinds/couples-diary#35]
e.g. when going from `/` to `/calendar/:year/:month`. This is because I wasn't previously able to merge the two paths.

**Comment by SimonKinds** [comment]
This issue is tracked in `react-router`: https://github.com/ReactTraining/react-router/issues/5866 
It works in my case, but causes a propType warning.

The easy fix is not valid because in nested routes the path would be given as array instead of string.

**Comment by SimonKinds** [comment]
Rather re-mount than have warnings in code. Let's keep this issue open though
